image: comp1531/basic:latest

stages:
  - lint
  - test

before_script:
  - npm install

linting:
  stage: lint
  script:
    - npm run lint

tests:
  stage: test
  script:
    - SERVER_LOG=$(mktemp)
    - npm run start >& $SERVER_LOG &
    - timeout 10s grep -q "⚡️ Server started on port" <(tail -f $SERVER_LOG) || exit 1
    - timeout -s SIGINT 180s npm run test || (cat $SERVER_LOG && exit 1)
    - kill -SIGINT %1
    - sleep 2
    - cat $SERVER_LOG
