version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3234:3234"